Repository glints-dev/glints-aries, pull requests merged in 2019-11, with the labels that each got.

#124 <Select> Add unit test and fix bug
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
  src/Input/Select/__snapshots__/Select.test.tsx.snap
Labels: :ballot_box_with_check: Tests, :bug: Bug

#126 <Button> Add unit tests and update props
  src/General/Button/Button.test.tsx
  src/General/Button/Button.tsx
  src/General/Button/LinkButton.tsx
  src/General/Button/__snapshots__/Button.test.tsx.snap
  tsconfig.json
Labels: :ballot_box_with_check: Tests

#136 ButtonStyle: Remove gray background on hover
  src/Style/General/ButtonStyle.ts
Labels: :bug: Bug

#137 TagStyle: Add border to default Tag
  src/Style/General/TagStyle.ts
Labels: :nail_care: UI Mismatch

#133 Feature/typography
  src/General/Typography/Paragraph.test.tsx
  src/General/Typography/Paragraph.tsx
  src/General/Typography/ParagraphStyles.ts
  src/General/Typography/Title.test.tsx
  src/General/Typography/Title.tsx
  src/General/Typography/TitleStyles.ts
  src/General/Typography/Typography.test.tsx
  src/General/Typography/Typography.tsx
  src/General/Typography/TypographyStory.tsx
  src/General/Typography/__snapshots__/Typography.test.tsx.snap
  src/General/Typography/index.ts
  stories/index.tsx
Labels: :ballot_box_with_check: Tests, :bulb: Feature Request

#138 StorybookComponent: Change import statement to require to workaround typescript error
  stories/StorybookComponent.tsx
Labels: :bug: Bug

#135 Feature/toggle switch
  dist/public/manifest.json
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  src/Input/ToggleSwitch/Styles.ts
  src/Input/ToggleSwitch/ToggleSwitch.tsx
  src/Input/ToggleSwitch/ToggleSwitchStory.tsx
  src/Input/ToggleSwitch/index.ts
  src/index.ts
  stories/index.tsx
  test/__tests__/__snapshots__/render-test.js.snap
Labels: :new: New Component

#144 Doc/improve typography and color stories
  src/General/Typography/TypographyStory.tsx
  stories/Utilities/ColorStory.tsx
Labels: :bookmark_tabs: Documentation

#142 Hotfix/tag and typography ui
  src/General/Typography/TitleStyles.ts
  src/Style/General/TagStyle.ts
  stories/General/TagStory.tsx
Labels: :nail_care: UI Mismatch

#127 <Modal> Add unit tests
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
  src/Display/Modal/__snapshots__/Modal.test.tsx.snap
  src/Style/Display/ModalStyle.ts
Labels: :ballot_box_with_check: Tests

#147 Test/text field
  package.json
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
  src/General/Button/__snapshots__/Button.test.tsx.snap
  src/General/Typography/__snapshots__/Typography.test.tsx.snap
  src/Input/TextField/TextField.test.tsx
  src/Input/TextField/TextField.tsx
  src/Input/TextField/__snapshots__/TextField.test.tsx.snap
  src/Style/Display/ModalStyle.ts
  src/Style/Input/TextFieldStyle.ts
  yarn.lock
Labels: :ballot_box_with_check: Tests

#145 Checkbox: Refactor to use hooks and add unit and snapshot tests
  src/Input/Checkbox/Checkbox.test.tsx
  src/Input/Checkbox/Checkbox.tsx
  src/Input/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#146 ES Module support
  .babelrc
  .babelrc.js
  .gitignore
  package.json
  src/Provider/index.tsx
  src/index.ts
  stories/General/TypographyStory.tsx
  stories/Input/ToggleSwitchStory.tsx
  stories/Provider.tsx
  stories/index.tsx
  webpack.config.js
  yarn.lock
Labels: :bulb: Feature Request

#153 Modal: Do not close modal if mousedown occurs inside modal but the subsequent mouseup occurs outside it
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
  src/Display/Modal/__snapshots__/Modal.test.tsx.snap
Labels: :bug: Bug

#159 Feat: loading icon
  src/Utils/IconLibrary.tsx
Labels: :bulb: Feature Request

#150 Colors: Update color library
  src/Style/Colors.ts
  src/index.ts
  stories/Utilities/ColorStory.tsx
Labels: :bulb: Feature Request, :straight_ruler: Extend Component

#157 Tag: Add unit and snapshot tests
  src/General/Tag/Tag.test.tsx
  src/General/Tag/Tag.tsx
  src/General/Tag/__snapshots__/Tag.test.tsx.snap
  src/Style/General/TagStyle.ts
Labels: :ballot_box_with_check: Tests

#151 Optimize icon size
  .babelrc.js
  .gitignore
  package.json
  src/Application/JobCard/JobCardDescription.tsx
  src/Application/JobCard/JobCardDetail.tsx
  src/Display/Accordion/AccordionPanel.tsx
  src/Display/Blockquote/Blockquote.tsx
  src/Display/Collapsible/Collapsible.tsx
  src/Display/Modal/Modal.tsx
  src/Display/Popover/Popover.tsx
  src/Display/Slider/LeftArrow.tsx
  src/Display/Slider/RightArrow.tsx
  src/Display/Toast/Toast.tsx
  src/General/Alert/Alert.tsx
  src/General/Icon/Icon.tsx
  src/General/Icon/LegacyIcon.tsx
  src/General/Icon/index.ts
  src/General/ProfilePicture/ProfilePicture.tsx
  src/Input/Datepicker/Datepicker.tsx
  src/Input/Select/Select.tsx
  src/Input/TextField/TextField.tsx
  src/Input/ToggleSwitch/ToggleSwitch.tsx
  src/Navigation/Dropdown/Dropdown.tsx
  src/Utils/Icon/IconLibrary.tsx
  src/Utils/Icon/generateIcons.ts
  src/index.ts
  stories/Application/JobOverviewStory.tsx
  stories/General/IconStory.tsx
  stories/General/TagStory.tsx
  stories/Input/OmniSearchStory.tsx
  stories/Input/SearchFilterStory.tsx
  stories/Navigation/DropdownStory.tsx
  tsconfig.json
  yarn.lock
Labels: :bulb: Feature Request

#162 Fix error for ToggleSwitchStory
  stories/Input/ToggleSwitchStory.tsx
Labels: :bug: Bug

#164 Fix: cannot close tooltip on ios < 13
  src/Display/Tooltip/Tooltip.tsx
Labels: :bug: Bug

#165 Fix: should close tooltip when click trigger button
  src/Display/Tooltip/Tooltip.tsx
Labels: :bug: Bug
