Repository glints-dev/glints-aries, pull requests merged in 2019-10, with the labels that each got.

#116 Display/Tabs: Add variant to Navigation Tabs and theme to the horizontal navigation tabs
  src/Display/Tabs/Tabs.tsx
  src/Style/Display/TabsStyle.ts
  src/Utils/StyleConfig.ts
  stories/Display/TabsStory.tsx
Labels: :straight_ruler: Extend Component

#120 Badge: Fix bug where a label of 0 causes the badge not to show
  src/General/Badge/Badge.tsx
  stories/General/BadgeStory.tsx
Labels: :bug: Bug

#117 Hotfix/tooltip bugs
  dist/public/manifest.json
  src/Display/Tooltip/Tooltip.tsx
  src/Style/Display/TooltipStyle.ts
Labels: :bug: Bug

#125 <Progress> Update unit test and fix bug
  src/Display/Progress/Progress.test.tsx
  src/Display/Progress/Progress.tsx
  src/Display/Progress/__snapshots__/Progress.test.tsx.snap
  src/Style/Display/ProgressStyle.ts
Labels: :ballot_box_with_check: Tests, :bug: Bug

#131 Docs/update prop definitions
  src/Application/Information/Title.tsx
  src/Display/EmployersBlockquote/EmployersBlockquote.tsx
  src/Display/Modal/Modal.tsx
  src/Display/Tabs/Tabs.tsx
  src/General/Brand/Brand.tsx
  src/General/Button/Button.tsx
  src/General/Button/DefaultButton.tsx
  src/General/Button/GhostButton.tsx
  src/General/Button/LinkButton.tsx
  src/General/Button/PrimaryButton.tsx
  src/General/Button/SecondaryButton.tsx
  src/General/Icon/Icon.tsx
  src/General/PsychedelicText/PsychedelicText.tsx
  src/General/Tag/Tag.tsx
  src/Input/AutoComplete/AutoComplete.tsx
  src/Input/OmniSearch/OmniSearch.tsx
  src/Input/SearchFilter/SearchFilter.tsx
  src/Input/Textarea/Textarea.tsx
  src/Layout/Grid/Col.tsx
  src/Layout/Grid/Row.tsx
  src/Style/Application/InformationStyle.ts
  src/Style/General/ButtonStyle.ts
  src/Style/Input/TextareaStyle.ts
  src/Utils/StyleConfig.ts
  stories/Application/InformationStory.tsx
  stories/Display/EmployersBlockquoteStory.tsx
  stories/Display/ModalStory.tsx
  stories/Display/PointingModalStory.tsx
  stories/Display/ProgressStory.tsx
  stories/Display/SwipeableStory.tsx
  stories/Display/TabsStory.tsx
  stories/Display/TooltipStory.tsx
  stories/General/BrandStory.tsx
  stories/General/ButtonStory.tsx
  stories/General/DividerStory.tsx
  stories/General/IconStory.tsx
  stories/Input/AutoCompleteStory.tsx
  stories/Input/OmniSearchStory.tsx
  stories/Input/RadioButtonStory.tsx
  stories/Input/SelectStory.tsx
  stories/Layout/GridStory.tsx
Labels: :bookmark_tabs: Documentation

#132 Update README - fix grammar issues
  README.md
Labels: :bookmark_tabs: Documentation

#134 Tooltip: Workaround for Tooltip not closing on iOS
  src/Display/Tooltip/Tooltip.tsx
Labels: :bug: Bug
