Repository glints-dev/glints-aries, pull requests merged in 2020-06, with the labels that each got.

#358 Slider: Add tests
  src/Display/Slider/LeftArrow.tsx
  src/Display/Slider/RightArrow.tsx
  src/Display/Slider/Slider.test.tsx
  src/Display/Slider/Slider.tsx
  src/Display/Slider/__snapshots__/Slider.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#359 Alert fix ui mismatch
  src/General/Alert/Alert.test.tsx
  src/General/Alert/Alert.tsx
  src/General/Alert/__snapshots__/Alert.test.tsx.snap
  src/Style/General/AlertStyle.ts
  stories/General/AlertStory.tsx
Labels: :nail_care: UI Mismatch

#363 Drawer: Add tests
  src/Navigation/Drawer/Drawer.test.tsx
  src/Navigation/Drawer/Drawer.tsx
  src/Navigation/Drawer/__snapshots__/Drawer.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#353 Brand: Convert to functional component
  src/General/Brand/Brand.tsx
Labels: Functional Component Conversion

#370 Select: defaultOpen & close behavior
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  src/Style/Input/SelectStyle.ts
  stories/Input/SelectStory.tsx
Labels: :straight_ruler: Extend Component

#373 Select: fix toLowerCase is not a function
  src/Input/Select/Select.tsx
Labels: :bug: Bug

#375 Select: Abort option select handler if there is no active option
  src/Input/Select/Select.tsx
Labels: :bug: Bug

#377 Drawer: Convert to functional component
  src/Navigation/Drawer/Drawer.tsx
Labels: Functional Component Conversion

#381 SearchFilter: fix the click event on SearchFilter.Item not working
  src/Input/SearchFilter/Context.ts
  src/Input/SearchFilter/SearchFilter.test.tsx
  src/Input/SearchFilter/SearchFilter.tsx
  src/Input/SearchFilter/SearchFilterItem.tsx
  src/Input/SearchFilter/__snapshots__/SearchFilter.test.tsx.snap
Labels: :bug: Bug

#382 Modal: Make onClose optional
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
Labels: :bulb: Feature Request

#383 Select: Handle non-string value
  src/Input/Select/Select.noTypeChecking.test.tsx
  src/Input/Select/Select.tsx
  src/Input/Select/__snapshots__/Select.noTypeChecking.test.tsx.snap
  src/Utils/canWarn.ts
Labels: :ballot_box_with_check: Tests

#387 Icon: Add phone icon
  src/Utils/Icon/IconLibrary.tsx
  src/index.ts
Labels: :bulb: Feature Request

#389 Icon: Add Telegram icon
  src/Utils/Icon/IconLibrary.tsx
  src/index.ts
Labels: :new: New Component

#393 Feature/add icons
  src/Utils/Icon/IconLibrary.tsx
  src/index.ts
Labels: :new: New Component

#394 Fix ShareArrowIcon
  src/Utils/Icon/IconLibrary.tsx
Labels: :bug: Bug
