Repository glints-dev/glints-aries, pull requests merged in 2020-01, with the labels that each got.

#184 Feature/refactor accordion
  src/Display/Accordion/Accordion.tsx
  src/Display/Accordion/AccordionPanel.tsx
  src/Style/Display/AccordionStyle.ts
  stories/Display/AccordionStory.tsx
Labels: :nail_care: UI Mismatch

#189 Hotfix/accordion
  src/Display/Accordion/Accordion.tsx
  src/Display/Accordion/AccordionPanel.tsx
  src/Style/Display/AccordionStyle.ts
  src/Utils/Icon/IconLibrary.tsx
Labels: :bug: Bug, :nail_care: UI Mismatch

#219 Icon: Add more props to increase customizability
  src/General/Icon/Icon.tsx
  stories/General/IconStory.tsx
Labels: :straight_ruler: Extend Component

#187 Select: Use min-width over width for options
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  src/Style/Input/SelectStyle.ts
Labels: :bug: Bug

#221 Modal: Don't Call onClose When Closed
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
Labels: :bug: Bug, Medium Priority
