Repository glints-dev/glints-aries, pull requests merged in 2020-02, with the labels that each got.

#182 Deprecate/job card
  .prettierignore
  package.json
  src/Application/JobCard/JobCard.tsx
  src/Application/JobCard/JobCardBody.tsx
  src/Application/JobCard/JobCardDescription.tsx
  src/Application/JobCard/JobCardDetail.tsx
  src/Application/JobCard/JobCardFooter.tsx
  src/Application/JobCard/JobCardHeader.tsx
  src/Application/JobCard/index.ts
  src/Style/Application/JobCardStyle.ts
  src/index.ts
  stories/Application/JobCardStory.tsx
  stories/Provider.tsx
  stories/index.tsx
  tsconfig.json
Labels: :toilet: Clean up

#226 Add `NumberInput` Component
  src/Input/NumberInput/NumberInput.test.tsx
  src/Input/NumberInput/NumberInput.tsx
  src/Input/NumberInput/__snapshots__/NumberInput.test.tsx.snap
  src/Input/NumberInput/index.ts
  src/Input/TextField/TextField.tsx
  src/Input/TextField/index.ts
  stories/Input/NumberInputStory.tsx
  stories/Input/TextFieldStory.tsx
  stories/index.tsx
Labels: :new: New Component, :straight_ruler: Extend Component

#228 disable typing Select shouldn't have cursor and open mobile keyboard
  src/Input/Select/Select.tsx
  yarn.lock
Labels: :bug: Bug

#230 Select: Call onOptionClick when enter key is pressed on an option
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
Labels: :bug: Bug

#188 Select Errors
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
  src/Style/Input/SelectStyle.ts
  stories/Input/SelectStory.tsx
Labels: :straight_ruler: Extend Component

#233 IconLibrary: Remove LockSolid icon fill color
  src/Utils/Icon/IconLibrary.tsx
Labels: :bug: Bug

#234 Hotfix/select active element
  src/Input/Select/Select.tsx
Labels: :bug: Bug

#235 TextField: Refactor export statement for TextFieldProps
  src/Input/TextField/index.ts
Labels: :bug: Bug

#241 added SSR support
  .babelrc.js
  package.json
  yarn.lock
Labels: :bug: Bug
