Repository glints-dev/glints-aries, pull requests merged in 2020-04, with the labels that each got.

#268 Scripts: Add count-imports scripts
  package.json
  scripts/count-imports/filters.ts
  scripts/count-imports/index.ts
  scripts/count-imports/parser.ts
  test/__tests__/filters.test.ts
  yarn.lock
Labels: :bulb: Feature Request

#269 Upgrade Packages
  package.json
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
  src/Display/Modal/__snapshots__/Modal.test.tsx.snap
  src/Display/Progress/__snapshots__/Progress.test.tsx.snap
  src/General/Button/__snapshots__/Button.test.tsx.snap
  src/General/Loading/Loading.tsx
  src/General/Tag/__snapshots__/Tag.test.tsx.snap
  src/General/Typography/__snapshots__/Typography.test.tsx.snap
  src/Input/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/Input/NumberInput/__snapshots__/NumberInput.test.tsx.snap
  src/Input/SearchFilter/SearchFilter.test.tsx
  src/Input/SearchFilter/__snapshots__/SearchFilter.test.tsx.snap
  src/Input/Select/Select.test.tsx
  src/Input/Select/SelectList.tsx
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  src/Input/TextField/__snapshots__/TextField.test.tsx.snap
  src/Input/Textarea/__snapshots__/Textarea.test.tsx.snap
  stories/Display/PointingModalStory.tsx
  stories/Display/PopoverStory.tsx
  stories/General/ButtonStory.tsx
  storybook-config/addons.js
  tsconfig.json
  yarn.lock
Labels: dependencies

#283 Dropdown: Update test
  src/Navigation/Dropdown/Dropdown.test.tsx
  src/Navigation/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#284 Dropdown: fix TS error
  src/Display/Slider/Slider.tsx
  src/Navigation/Dropdown/Dropdown.tsx
Labels: :bug: Bug

#272 Set up Github Actions
  .eslintrc.json
  .github/release-drafter.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/validate.yml
  package.json
  src/Display/Progress/WarningMessageUtils.ts
  src/Input/ToggleSwitch/Styles.ts
  src/Style/Display/ProgressStyle.ts
  src/Style/General/ButtonStyle.ts
  stories/Display/AccordionStory.tsx
  stories/Display/ModalStory.tsx
  stories/Display/PointingModalStory.tsx
  stories/Display/PopoverStory.tsx
  stories/General/ButtonStory.tsx
  stories/General/IconStory.tsx
  stories/General/PsychedelicTextStory.tsx
  stories/Input/NumberInputStory.tsx
  stories/Input/SelectStory.tsx
  stories/Input/TextFieldStory.tsx
  stories/StorybookComponent.tsx
  stories/Utilities/ColorStory.tsx
  tsconfig.declaration.json
  tsconfig.json
Labels: :bulb: Feature Request

#291 Github Actions: fix publish failed
  .github/workflows/publish.yml
Labels: :bug: Bug

#299 Tests/tooltip divider grid colors
  src/Display/Tooltip/Tooltip.test.tsx
  src/Display/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  src/General/Divider/Divider.test.tsx
  src/General/Divider/__snapshots__/Divider.test.tsx.snap
  src/Layout/Grid/Grid.test.tsx
  src/Layout/Grid/__snapshots__/Grid.test.tsx.snap
  src/Style/Colors.test.ts
Labels: :ballot_box_with_check: Tests

#294 Loading: Add tests
  src/General/Loading/Loading.test.tsx
  src/General/Loading/__snapshots__/Loading.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#293 RadioButton: Add tests
  src/Input/RadioButton/RadioButton.test.tsx
  src/Input/RadioButton/__snapshots__/RadioButton.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#302 Select: Fix mismatch
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  src/Style/Input/SelectStyle.ts
  stories/Input/SelectStory.tsx
Labels: :nail_care: UI Mismatch

#300 Tests: Add tests for heading and device size
  src/General/Heading/Heading.test.tsx
  src/General/Heading/Heading.tsx
  src/General/Heading/__snapshots__/Heading.test.tsx.snap
  src/Utils/StyleConfig.test.ts
Labels: :ballot_box_with_check: Tests

#296 Collapsible: Convert to functional component
  src/Display/Collapsible/Collapsible.tsx
Labels: Functional Component Conversion

#303 Feature/fix button mismatch
  src/General/Button/Button.tsx
  src/General/Button/PrimaryButton.tsx
  src/General/Button/__snapshots__/Button.test.tsx.snap
  src/General/Button/index.tsx
  src/Input/SearchFilter/__snapshots__/SearchFilter.test.tsx.snap
  src/Style/General/ButtonStyle.ts
  src/Utils/StyleConfig.ts
  stories/General/ButtonStory.tsx
Labels: :nail_care: UI Mismatch

#309 Tests: Ignore test.ts file in build process, add coverage command
  package.json
  src/Style/Colors.test.ts
  src/Style/__snapshots__/Colors.test.ts.snap
Labels: :ballot_box_with_check: Tests

#310 Feature/checkbox label prop
  src/Input/Checkbox/Checkbox.test.tsx
  src/Input/Checkbox/Checkbox.tsx
  stories/Input/CheckboxStory.tsx
Labels: :straight_ruler: Extend Component

#312 Icon: add HomeIcon
  src/Utils/Icon/IconLibrary.tsx
  src/Utils/StyleConfig.ts
  src/index.ts
Labels: :new: New Component
