Repository glints-dev/glints-aries, pull requests merged in 2020-09, with the labels that each got.

#470 Popover: Convert to functional component
  src/Display/Popover/Popover.tsx
Labels: Functional Component Conversion

#473 Checkbox: remove the gradient shadow inside checkbox
  src/Input/Checkbox/CheckboxStyle.ts
  src/Input/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: :bug: Bug

#476 Modal: Add aria-label for close button
  src/Display/Gallery/__snapshots__/Gallery.test.tsx.snap
  src/Display/Modal/Modal.tsx
  src/Display/Modal/__snapshots__/Modal.test.tsx.snap
Labels: :straight_ruler: Extend Component
