Repository glints-dev/glints-aries, pull requests merged in 2020-03, with the labels that each got.

#240 Feature/icon inherit color
  src/Display/Modal/__snapshots__/Modal.test.tsx.snap
  src/General/Icon/Icon.test.tsx
  src/General/Icon/Icon.tsx
  src/General/Icon/__snapshots__/Icon.test.tsx.snap
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  stories/General/IconStory.tsx
  stories/StorybookComponent.tsx
Labels: :straight_ruler: Extend Component

#238 Textarea: Convert to functional component
  src/Input/Textarea/Textarea.tsx
Labels: Functional Component Conversion

#245 Modal: Convert to functional component
  src/Display/Modal/Modal.tsx
Labels: Functional Component Conversion

#152 Alert: Fix the closing of the alert on clicking below the close icon
  src/Style/General/AlertStyle.ts
Labels: :bug: Bug

#252 Select: Convert to functional component
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
  src/Input/Select/SelectList.tsx
  src/Input/Select/__snapshots__/Select.test.tsx.snap
Labels: Functional Component Conversion
