Repository glints-dev/glints-aries, pull requests merged in 2020-05, with the labels that each got.

#311 Modal: children should not be mounted when visible
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
Labels: :bulb: Feature Request

#316 Revert "Modal: children should not be mounted when visible"
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
Labels: :bug: Bug

#318 Swipeable: Hide scrollbar on firefox
  src/Style/Display/SwipeableStyle.ts
Labels: :bug: Bug

#324 Tests/profile picture
  package.json
  src/General/ProfilePicture/ProfilePicture.test.tsx
  src/General/ProfilePicture/__snapshots__/ProfilePicture.test.tsx.snap
  yarn.lock
Labels: :ballot_box_with_check: Tests

#328 Swipeable: make scrollbar visible on desktop
  src/Style/Display/SwipeableStyle.ts
  stories/Display/SwipeableStory.tsx
Labels: :bulb: Feature Request

#321 Tabs Component: Add tests for the tabs component
  src/Display/Tabs/Tabs.test.tsx
  src/Display/Tabs/Tabs.tsx
  src/Display/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#329 ProfilePicture: Add test case for non-editable profile picture
  src/General/ProfilePicture/ProfilePicture.test.tsx
  src/General/ProfilePicture/__snapshots__/ProfilePicture.test.tsx.snap
Labels: :ballot_box_with_check: Tests

#315 Button: rename buttons & deprecate props
  src/General/Button/Button.test.tsx
  src/General/Button/Button.tsx
  src/General/Button/GhostButton.tsx
  src/General/Button/SecondaryButton.tsx
  src/General/Button/SolidButton.tsx
  src/General/Button/SolidShadowButton.tsx
  src/General/Button/__snapshots__/Button.test.tsx.snap
  src/General/Button/index.tsx
  src/Input/SearchFilter/__snapshots__/SearchFilter.test.tsx.snap
  src/Style/General/ButtonStyle.ts
  src/Utils/StyleConfig.ts
  stories/Display/ModalStory.tsx
  stories/Display/ToastStory.tsx
  stories/General/AlertStory.tsx
  stories/General/ButtonStory.tsx
  stories/Navigation/DrawerStory.tsx
Labels: :warning: Breaking Changes

#323 Tag: align with GDS
  src/General/Tag/ActionTags/AddTag.tsx
  src/General/Tag/ActionTags/ResetTag.tsx
  src/General/Tag/BasicTag.tsx
  src/General/Tag/Tag.test.tsx
  src/General/Tag/Tag.tsx
  src/General/Tag/__snapshots__/Tag.test.tsx.snap
  src/Style/General/TagStyle.ts
  stories/Display/TooltipStory.tsx
  stories/General/TagStory.tsx
Labels: :nail_care: UI Mismatch, :straight_ruler: Extend Component

#331 Release Drafter: add Breaking Changes category
  .github/release-drafter.yml
Labels: :bulb: Feature Request

#327 Alert: functional component
  src/General/Alert/Alert.test.tsx
  src/General/Alert/Alert.tsx
Labels: Functional Component Conversion

#336 Button: backward compatible for legacy variant
  src/General/Button/Button.test.tsx
  src/General/Button/Button.tsx
Labels: :straight_ruler: Extend Component

#267 Checkbox: Add a new parameter of small for the checkboxes
  src/Input/Checkbox/Checkbox.test.tsx
  src/Input/Checkbox/Checkbox.tsx
  src/Input/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/Style/Input/CheckboxStyle.ts
  src/Utils/Icon/IconLibrary.tsx
  src/index.ts
  stories/Input/CheckboxStory.tsx
Labels: :straight_ruler: Extend Component

#344 Select: Refactor and fix bugs
  src/Input/Select/Select.test.tsx
  src/Input/Select/Select.tsx
  src/Input/Select/SelectList.tsx
  src/Input/Select/__snapshots__/Select.test.tsx.snap
  stories/Input/SelectStory.tsx
Labels: :bug: Bug, :straight_ruler: Extend Component

#345 Modal: won't mount children when visible
  src/Application/Gallery/Gallery.test.tsx
  src/Application/Gallery/Gallery.tsx
  src/Display/Modal/Modal.test.tsx
  src/Display/Modal/Modal.tsx
Labels: :bug: Bug

#351 RadioButton: Extend component props and styles
  src/Input/RadioButton/RadioButton.tsx
  src/Input/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/Style/Input/RadioButtonStyle.ts
  stories/Input/RadioButtonStory.tsx
Labels: :straight_ruler: Extend Component
