Repository glints-dev/glints-aries, pull requests merged in 2021-01, with the labels that each got.

#563 Storybook6: ProfilePicture
  src/General/ProfilePicture/ProfilePicture.stories.tsx
  src/General/ProfilePicture/ProfilePicture.tsx
Labels: Documentation

#569 Slider: Make slider dots margin responsive
  src/Display/Slider/SliderStyle.ts
  src/Display/Slider/__snapshots__/Slider.test.tsx.snap
Labels: UI Mismatch

#579 Automate S3 deployment
  .github/workflows/s3-deploy-legacy.yml
  .github/workflows/s3-deploy.yml
Labels: Feature Request

#586 Button: fix forward ref
  src/General/Button/Button.test.tsx
  src/General/Button/Button.tsx
  src/General/Button/GhostButton.tsx
  src/General/Button/LinkButton.tsx
  src/General/Button/SolidButton.tsx
  src/General/Button/SolidShadowButton.tsx
Labels: Bug

#578 Feature/box story migration
  src/Layout/Box/Box.stories.tsx
  src/Layout/Box/BoxStoryStyle.tsx
  src/Layout/Box/constants.ts
  src/Layout/Box/types.ts
  src/Layout/Flex/Flex.stories.tsx
  src/Layout/Flex/FlexStoryStyle.tsx
  src/Layout/Flex/index.tsx
  src/Layout/Flex/types.ts
  stories/Layout/BoxStory/BoxSpaceStory.tsx
  stories/Layout/SpacingStory.tsx
  stories/Utilities/ShadowStory.tsx
Labels: Documentation
