Repository glints-dev/glints-aries, pull requests merged in 2023-08, with the labels that each got.

#919 Icons: add new icons
  src/@next/Icon/icons/icons.ts
  src/@next/Icon/icons/ri-building-fill.svg
  src/@next/Icon/icons/ri-suitcase3-fill.svg
  src/@next/Icon/icons/ri-user5-fill.svg
Labels: New Icons

#920 Portal: export component
  src/@next/Portal/index.ts
  src/@next/index.ts
Labels: Extend Component

#921 fix: import/export type and interface issue
  .eslintrc.json
  .nvmrc
  .prettierrc.json
  README.md
  SECURITY.md
  package.json
  src/@next/Banner/index.tsx
  src/@next/IndexTable/IndexTable.tsx
  src/@next/Menu/components/index.ts
  src/@next/Pagination/index.ts
  src/@next/Skeleton/components/index.ts
  src/@next/index.ts
  src/General/Brand/Brand.tsx
  src/General/ProfilePicture/ProfilePictureStyle.ts
  src/Utils/Colors.stories.mdx
  src/index.ts
  tsconfig.json
  typings/custom.d.ts
Labels: Clean up

#922 fix: Adjust Utilities in storybook to display correct ordering
  src/@next/utilities/borderRadius/BorderRadius.stories.mdx
  src/@next/utilities/borderRadius/BorderRadius.ts
  src/@next/utilities/spacing/Spacing.stories.mdx
  src/@next/utilities/spacing/Spacing.ts
Labels: Clean up

#927 Icons: add ri-download-line icon
  src/@next/Icon/icons/icons.ts
  src/@next/Icon/icons/ri-download-line.svg
Labels: New Icons

#926 DataTable: allow reactnode as datatable heading
  src/@next/DataTable/DataTable.tsx
  src/@next/DataTable/TableHeader.tsx
Labels: Extend Component

#948 DataTable: add class to container
  src/@next/DataTable/DataTable.tsx
Labels: Extend Component

#940 DataTable: fix wrong condition for console.warn
  src/@next/DataTable/DataTable.tsx
Labels: Clean up

#951 Select: prop to trigger action when select is clicked
  src/@next/Select/Select.tsx
  src/@next/Select/components/Activator/ActivatorSelect.tsx
Labels: Extend Component
